- name: Installing latest virtualenv
  pip: >
    name=virtualenv
    state=latest
    executable=/usr/bin/pip3
  become: yes
  become_user: root
  tags: virtualenv

- name: Create python virtual environment
  shell: "virtualenv -p /usr/local/bin/python{{ venv.python.ver }} {{ project_venv_dir }}"
  become: no
  tags: virtualenv

- name: Upgrade pip and setuptools
  pip: >
    name={{ item }}
    executable="{{ project_venv_dir }}/bin/pip"
    state=latest
  with_items:
    - pip
    - setuptools
  become: no
  tags: virtualenv