# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPDFReportTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_template', models.TextField(verbose_name='Template')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_template', to='owners.Owner', verbose_name='Owner')),
            ],
            options={
                'ordering': ('owner_id',),
            },
        ),
    ]
