# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_ownerpdfreporttheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Default from email address'),
        ),
    ]
