# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 09:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_owner_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerEmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Default from email address')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('host', models.CharField(default='smtp.mail.eu-west-1.awsapps.com', max_length=100, verbose_name='Host')),
                ('port', models.PositiveSmallIntegerField(default=465, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Port')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='Use ssl?')),
                ('use_tsl', models.BooleanField(default=False, verbose_name='Use tsl?')),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='from_email',
        ),
        migrations.AddField(
            model_name='owneremailconfig',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='owners.Owner'),
        ),
    ]
