# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='yrly_avg_met',
            field=models.CharField(choices=[(0, 'SBI 2018'), (1, 'PHE for dwelling'), (2, 'PHE for workplace')], default=0, max_length=30, verbose_name='Yearly Average method'),
        ),
    ]
