# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-24 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_owner_yrly_avg_met'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='yrly_avg_met',
            field=models.CharField(choices=[('sbi_dk_2018', 'SBI 2018'), ('phe_uk_2018_dwe', 'PHE for dwelling'), ('phe_uk_2018_wrk', 'PHE for workplace')], default='sbi_dk_2018', max_length=30, verbose_name='Yearly Average method'),
        ),
    ]
