# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_email_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_html_template_da',
            field=models.TextField(blank=True, help_text='HTML template', null=True, verbose_name='Email Body HTML Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_html_template_en',
            field=models.TextField(blank=True, help_text='HTML template', null=True, verbose_name='Email Body HTML Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_html_template_nn',
            field=models.TextField(blank=True, help_text='HTML template', null=True, verbose_name='Email Body HTML Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_html_template_sv',
            field=models.TextField(blank=True, help_text='HTML template', null=True, verbose_name='Email Body HTML Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_template_da',
            field=models.TextField(blank=True, null=True, verbose_name='Email Body Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_template_en',
            field=models.TextField(blank=True, null=True, verbose_name='Email Body Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_template_nn',
            field=models.TextField(blank=True, null=True, verbose_name='Email Body Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_template_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Email Body Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_subject_template_da',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Subject Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_subject_template_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Subject Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_subject_template_nn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Subject Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_subject_template_sv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Subject Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='name_da',
            field=models.CharField(help_text='This is just used for organisational purposes', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='name_en',
            field=models.CharField(help_text='This is just used for organisational purposes', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='name_nn',
            field=models.CharField(help_text='This is just used for organisational purposes', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='name_sv',
            field=models.CharField(help_text='This is just used for organisational purposes', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
