# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20171102_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationeventtype',
            name='name_da',
        ),
        migrations.RemoveField(
            model_name='communicationeventtype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='communicationeventtype',
            name='name_nn',
        ),
        migrations.RemoveField(
            model_name='communicationeventtype',
            name='name_sv',
        ),
    ]
