# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170609_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lead',
            field=models.TextField(blank=True, help_text='Lead paragraph', verbose_name='Lead'),
        ),
    ]
