# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170609_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scan_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='scan_code'),
        ),
    ]
