# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_product_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lead',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, verbose_name='Lead'),
        ),
    ]
