# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_product_scan_code'),
        ('catalogue', '0014_auto_20170922_1323'),
    ]

    operations = [
    ]
