# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_dosimeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_usage',
            field=models.TextField(blank=True,
                                   help_text='Usage instructions. (Dosimeters Only)',
                                   verbose_name='Product usage'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_video_id',
            field=models.CharField(blank=True,
                                   help_text='Example: Hg9MMVBHPAk)',
                                   max_length=255),
        ),
    ]
