# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_line_device_barcode'),
        ('catalogue', '0015_merge_20170925_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosimeter',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='Serial number')),
                ('result', models.CharField(blank=True, max_length=50, verbose_name='Result')),
                ('uncertainty', models.CharField(blank=True, max_length=50, verbose_name='Uncertainty')),
                ('yearly_avg', models.CharField(blank=True, max_length=50, verbose_name='Yearly avg')),
                ('report_url', models.URLField(blank=True, null=True, verbose_name='Report link')),
                ('measurement_start_date', models.DateField(blank=True, null=True, verbose_name='Measurement start date')),
                ('measurement_end_date', models.DateField(blank=True, null=True, verbose_name='Measurement end date')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Floor')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosimeters', to='order.Line', verbose_name='Line')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
