# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_line_device_barcode'),
        ('catalogue', '0020_auto_20171009_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultProduct',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='Serial number')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.Line', verbose_name='Line')),
            ],
            options={
                'ordering': ('-line__order__date_placed', '-created'),
            },
        ),
    ]
