# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_defaultproduct'),
    ]

    operations = [

    ]
