# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20171011_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosimeter',
            options={'ordering': ('created',)},
        ),
    ]
