# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_from_20171005_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosimeter',
            options={'ordering': ('-line__order__date_placed', '-created')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='scan_code',
        ),
    ]
