# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20171012_0625'),
    ]

    operations = [
    ]
