# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20171012_1809'),
    ]

    operations = [

    ]
