# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20171012_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_da',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_nb',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_da',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nb',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_da',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nb',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_da',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_en',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_nb',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_sv',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usage_da',
            field=models.TextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usage_en',
            field=models.TextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usage_nb',
            field=models.TextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usage_sv',
            field=models.TextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_da',
            field=models.TextField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_en',
            field=models.TextField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_nb',
            field=models.TextField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_da',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_nb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_sv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
