# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20171023_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_nn',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nn',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nn',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_nn',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_usage_nn',
            field=models.TextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_nn',
            field=models.TextField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_nn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
