# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 09:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20171023_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lead',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Lead paragraph', max_length=450, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_da',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_nn',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_sv',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_usage',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', verbose_name='Product usage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_usage_da',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_usage_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_usage_nn',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_usage_sv',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Usage instructions. (Dosimeters Only)', null=True, verbose_name='Product usage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification_da',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification_nn',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification_sv',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Specification'),
        ),
    ]
