# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20171023_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lead',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_da',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_en',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_nn',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_sv',
            field=models.TextField(blank=True, help_text='Lead paragraph', max_length=450, null=True, verbose_name='Lead'),
        ),
    ]
