# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20171023_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosimeter',
            name='floor',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Basement'), (0, 'Living room'), (1, '1st floor'), (2, '2nd floor'), (3, '3rd floor or higher')], null=True, verbose_name='Floor'),
        ),
    ]
