# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_change_product_class_for_dosimeters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosimeter',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('on_client_side', 'On client side'), ('on_store_side', 'On store side'), ('on_lab_side', 'On lab side'), ('completed', 'Completed')], default='unknown', max_length=20, verbose_name='Status'),
        ),
    ]
