# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_auto_20171031_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultproduct',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='dosimeter',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Serial number'),
        ),
    ]
