# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20171103_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_num_for_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Minimal number for order.'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight of product in grams.', null=True, verbose_name='Weight'),
        ),
    ]
