# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


def set_null(apps, schema_editor):
    Dosimeter = apps.get_model('catalogue', 'Dosimeter')

    # Set `<null>` to all blank `result` and `uncertainty` fields.
    Dosimeter.objects.filter(result='').update(result=None)
    Dosimeter.objects.filter(uncertainty='').update(uncertainty=None)


def unset_null(apps, schema_editor):
    Dosimeter = apps.get_model('catalogue', 'Dosimeter')

    # Set blank string to all nullable `result` and `uncertainty` fields.
    Dosimeter.objects.filter(result=None).update(result='')
    Dosimeter.objects.filter(uncertainty=None).update(uncertainty='')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_auto_20171109_0754'),
    ]

    operations = [

        migrations.AlterField(
            model_name='dosimeter',
            name='result',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Result', max_length=255),
        ),
        migrations.AlterField(
            model_name='dosimeter',
            name='uncertainty',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Uncertainty', max_length=255),
        ),

        migrations.RunPython(set_null, unset_null),

    ]
