# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_auto_20171113_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosimeter',
            name='result',
            field=models.FloatField(blank=True, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='dosimeter',
            name='uncertainty',
            field=models.FloatField(blank=True, null=True, verbose_name='Uncertainty'),
        ),
    ]
