# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_update_dosimeter_fields'),
    ]

    operations = [
        migrations.RenameField('Dosimeter', 'result', 'concentration'),
        migrations.AlterField(
            model_name='dosimeter',
            name='concentration',
            field=models.FloatField(blank=True, null=True, verbose_name='Concentration'),
        ),
    ]
