# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_auto_20171113_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosimeter',
            name='report_url',
        ),
    ]
