# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_remove_dosimeter_yearly_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosimeter',
            name='active_area',
            field=models.BooleanField(default=True, verbose_name='Active Area'),
        ),
    ]
