# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_dosimeter_active_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosimeter',
            name='use_raw_concentration',
            field=models.BooleanField(default=False, verbose_name='Should we use raw concentration?'),
        ),
    ]
