# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-26 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosimeter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
