# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0047_dosimeter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosimeter',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User who made the last modification of the dosimeter'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of last edition'),
        ),
    ]
