# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_auto_20180701_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosimeter',
            name='is_invoiced',
            field=models.BooleanField(default=True, verbose_name='Is invoiced?'),
        ),
        migrations.AddField(
            model_name='dosimeter',
            name='service_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Service price'),
        ),
    ]
