# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_auto_20181030_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosimeter',
            name='use_raw_concentration',
            field=models.BooleanField(default=False, verbose_name='Should we use raw concentration and uncertainty?'),
        ),
    ]
