# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_auto_20180619_0936'),
        ('catalogue', '0050_auto_20190401_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Batch_Dosimeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Batch')),
            ],
        ),
        migrations.AlterField(
            model_name='dosimeter',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('created', 'Created'), ('ready_for_packaging', 'Ready_for_packaging'), ('shipped_to_distributor', 'Shipped_to_distributor'), ('recieved_from_distributor', 'Recieved_from_distributor'), ('on_client_side', 'On client side'), ('on_store_side', 'On store side'), ('on_lab_side', 'On lab side'), ('completed', 'Completed')], default='unknown', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='batch_dosimeter',
            name='dosimeter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Dosimeter'),
        ),
    ]
