# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-30 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_auto_20190830_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(default=False, max_length=255, verbose_name='Batch Name'),
        ),
    ]
