# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-31 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_auto_20190831_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosimeter',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('created', 'Created'), ('ready_for_packaging', 'Ready_for_packaging'), ('shipped_to_distributor', 'Shipped_to_distributor'), ('recieved_from_distributor', 'Recieved_from_distributor'), ('on_client_side', 'On client side'), ('on_store_side', 'On store side'), ('on_lab_side', 'On lab side'), ('completed', 'Completed')], default='unknown', max_length=30, verbose_name='Status'),
        ),
    ]
