# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-02 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_auto_20191002_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 2, 1, 3, 27, 127785, tzinfo=utc), null=True, verbose_name='Date of creation'),
        ),
    ]
