# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-02 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_batch_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_description',
            field=models.CharField(blank=True, max_length=512, verbose_name='Batch Description'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 2, 1, 5, 21, 88531, tzinfo=utc), null=True, verbose_name='Date of creation'),
        ),
    ]
