# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-03 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_auto_20191002_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 11, 46, 58, 468270, tzinfo=utc), null=True, verbose_name='Date of creation'),
        ),
    ]
