# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_auto_20191003_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
    ]
