# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0060_dosimeternote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosimeter',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosimeters', to='order.Line', verbose_name='Line'),
        ),
    ]
