# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-18 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0059_dosimeter_non_mandatory_orderline'),
        ('catalogue', '0061_auto_20191017_0849'),
    ]

    operations = [
    ]
