# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_laboratory',
            field=models.BooleanField(default=False, verbose_name='laboratory status'),
        ),
    ]
