# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171103_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='partner status'),
        ),
    ]
