# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180202_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('imported', 'Imported'), ('dashboard', 'Dashboard')], default='web', max_length=20, verbose_name='Source'),
        ),
    ]
