---

- name: Add apt key for nodejs
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  tags: nodejs

- name: Install nodejs LTS
  apt: >
    update_cache=yes
    name={{ item }}
    state=present
  with_items:
    - nodejs
  become: yes
  become_user: root
  tags: nodejs

- name: Install npm globally
  npm: >
    name=npm
    global=yes
    state=latest
  become: yes
  become_user: root
  tags: nodejs