# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_dosimetercondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosimeterBenefit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('offer.benefit',),
        ),
    ]
