# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_delete_vouchercustomcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='description_da',
            field=models.TextField(blank=True, help_text='This is displayed on the offer browsing page', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='description_en',
            field=models.TextField(blank=True, help_text='This is displayed on the offer browsing page', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='description_nb',
            field=models.TextField(blank=True, help_text='This is displayed on the offer browsing page', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='description_sv',
            field=models.TextField(blank=True, help_text='This is displayed on the offer browsing page', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='name_da',
            field=models.CharField(help_text="This is displayed within the customer's basket", max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='name_en',
            field=models.CharField(help_text="This is displayed within the customer's basket", max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='name_nb',
            field=models.CharField(help_text="This is displayed within the customer's basket", max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='name_sv',
            field=models.CharField(help_text="This is displayed within the customer's basket", max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='range',
            name='description_da',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='description_nb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='description_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='name_da',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='range',
            name='name_en',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='range',
            name='name_nb',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='range',
            name='name_sv',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
    ]
