# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_auto_20171023_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='description_nn',
            field=models.TextField(blank=True, help_text='This is displayed on the offer browsing page', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='name_nn',
            field=models.CharField(help_text="This is displayed within the customer's basket", max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='range',
            name='description_nn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='name_nn',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
    ]
