# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_auto_20171023_0637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherCustomBenefit',
        ),
    ]
