# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=255, verbose_name='Client Username')),
                ('client_password', models.CharField(max_length=255, verbose_name='Client Password')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('organization_id', models.CharField(max_length=255, verbose_name='Organization id')),
                ('meta_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Meta fields')),
            ],
            options={
                'verbose_name_plural': 'Accounting',
            },
        ),
    ]
