# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-31 12:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_auto_20190129_1014'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingLedgerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('external_id', models.CharField(max_length=255)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Meta fields')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_ledgers', to='order.Order')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
