# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20180823_0850'),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLabel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255, verbose_name='Label number')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='order.Order', verbose_name='Label')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
