# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_shipmentlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_status',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_status_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_status_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipmentlabel',
            name='number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Label number'),
        ),
    ]
