# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-03 11:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20180823_0850'),
        ('deliveries', '0003_auto_20181119_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentReturn',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Data')),
                ('current_status', models.CharField(blank=True, max_length=25)),
                ('current_status_text', models.CharField(blank=True, max_length=255)),
                ('current_status_registered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_return', to='order.Order', verbose_name='Order')),
            ],
            options={
                'default_related_name': 'shipment_return',
            },
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={},
        ),
    ]
