# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
    ]

    operations = [
    ]
