# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 08:12
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.postgres.operations import HStoreExtension



class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20170925_1423'),
    ]

    operations = [
        HStoreExtension()
    ]
