# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 08:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170926_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='device_barcode',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
