# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_line_device_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='device_barcode',
        ),
    ]
