# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_line_device_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='report_pdf',
            field=models.SlugField(blank=True, null=True, verbose_name='Report link'),
        ),
    ]
