# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_line_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='report_pdf',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='media/dosimeters_reports', verbose_name='Report file'),
        ),
    ]
