# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20171023_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='report_pdf',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='media/dosimeters_pdf_reports', verbose_name='Report file'),
        ),
    ]
