# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20171023_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='report_pdf',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='dosimeters_pdf_reports', verbose_name='Report file'),
        ),
    ]
