# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20171024_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='dosimeters_pdf_reports', verbose_name='Report file'),
        ),
    ]
