# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 13:26
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20171024_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in the international format.', max_length=15, validators=[common.validators.PhoneNumberValidator()], verbose_name='Phone Number'),
        ),
    ]
