# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20171026_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_id',
            field=models.CharField(blank=True, help_text='Code for checking where is order now.', max_length=255, verbose_name='Shipping ID'),
        ),
    ]
