# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_shipping_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='report_pdf',
        ),
    ]
