# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_set_title_and_upc_for_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner_order_id',
            field=models.CharField(blank=True, help_text="ID of order in the partner's system.", max_length=255, verbose_name='Partner order ID'),
        ),
    ]
