# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_partner_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is approved'),
        ),
    ]
