# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('order', '0021_order_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Owner', verbose_name='Owner'),
        ),
    ]
