# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0022_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_report_sent',
            field=models.BooleanField(default=False, verbose_name='Is report sent?'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_reported_by_partner',
            field=models.BooleanField(default=False, verbose_name='Reported by partner?'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_who_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who approved the order.'),
        ),
    ]
