# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20180527_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved date'),
        ),
    ]
