# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20180814_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_weird_outlier',
            field=models.BooleanField(default=False, verbose_name='Outlier concentration'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_weird_overlap_1',
            field=models.BooleanField(default=False, verbose_name='Level 1 concentration overlap'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_weird_overlap_2',
            field=models.BooleanField(default=False, verbose_name='Level 2 concentration overlap'),
        ),
    ]
