# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 19:39
from __future__ import unicode_literals

from django.db import migrations

from oscar.core.loading import get_model

def recalculate_weirdness(apps, schema_editor):
    Order = get_model('order', 'Order')
    for order in Order.objects.only('is_weird_outlier', 'is_weird_overlap_1', 'is_weird_overlap_2'):
        order.update_weirdness_statuses()
        order.save(update_fields=['is_weird_outlier', 'is_weird_overlap_1', 'is_weird_overlap_2'])

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20180815_1151'),
    ]

    operations = [
        migrations.RunPython(recalculate_weirdness),
    ]
