# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20180815_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_weird_outlier',
            field=models.BooleanField(default=False, verbose_name='Suspect result - outlier concentration'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_weird_overlap_1',
            field=models.BooleanField(default=False, verbose_name='Suspect result - Level 1 concentration overlap'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_weird_overlap_2',
            field=models.BooleanField(default=False, verbose_name='Suspect result - Level 2 concentration overlap'),
        ),
        migrations.AlterField(
            model_name='order',
            name='not_weird',
            field=models.BooleanField(default=False, verbose_name='Results are correct even though suspect?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='not_weird_explanation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Why results are correct even though suspect'),
        ),
    ]
