# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20180823_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_return_id',
            field=models.CharField(blank=True, help_text='Code for return label.', max_length=255, verbose_name='Shipment ID for Return Label'),
        ),
    ]
