# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_order_shipping_return_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_exists_accounting',
            field=models.BooleanField(default=False, help_text='Show if an order has been registered in accounting system', verbose_name='Is exist'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
    ]
