# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 09:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170609_1902'),
        ('common', '0002_contactusmessage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_page', models.BooleanField(default=False, help_text='Means that object will be have a different page on the site.', verbose_name='Is page')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/category_section/', verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/category_section/', verbose_name='Image')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalogue.Category', verbose_name='Categories')),
            ],
        ),
    ]
