# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_categorysection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysection',
            name='is_page',
        ),
    ]
