# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_categorysection_is_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysection',
            options={'ordering': ['position', '-title']},
        ),
        migrations.AddField(
            model_name='categorysection',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position in list'),
        ),
        migrations.AlterField(
            model_name='categorysection',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
