# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170914_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysection',
            options={'ordering': ('position', '-title')},
        ),
    ]
