# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20170914_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysection',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
    ]
