# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20170914_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
