# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_consultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Is answered'),
        ),
    ]
