# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_consultationrequest_is_answered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsMessage',
            new_name='ContactUsRequest',
        ),
    ]
