# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 14:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20170926_1543'),
    ]

    operations = [

    ]
