# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 06:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20171003_1400'),
    ]

    operations = [

    ]
