# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 14:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20171012_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysection',
            name='content_da',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='content_nb',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='content_sv',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='title_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='title_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='title_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
