# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_migrate_data_for_translation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysection',
            name='content_nb',
        ),
        migrations.RemoveField(
            model_name='categorysection',
            name='title_nb',
        ),
    ]
