# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 06:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20171023_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysection',
            name='content_nn',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='title_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
