# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_migrate_data_for_translation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosimeterPDFReportTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='Body')),
                ('body_en', models.TextField(null=True, verbose_name='Body')),
                ('body_da', models.TextField(null=True, verbose_name='Body')),
                ('body_sv', models.TextField(null=True, verbose_name='Body')),
                ('body_nn', models.TextField(null=True, verbose_name='Body')),
                ('min_concentration', models.PositiveSmallIntegerField(default=0, verbose_name='Minimal Concentration')),
                ('max_concentration', models.PositiveSmallIntegerField(default=0, verbose_name='Maximal Concentration')),
            ],
            options={
                'ordering': ('min_concentration',),
            },
        ),
    ]
