# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_ownerpdfreporttheme'),
        ('common', '0021_dosimeterpdfreporttheme'),
    ]

    def sync_themes(apps, schema_editor):
        Owner = apps.get_model("owners", "Owner")
        DosimeterPDFReportTheme = apps.get_model("common", "DosimeterPDFReportTheme")

        owner = Owner.objects.filter(is_default=True).first() or Owner.objects.first()
        if owner:
            DosimeterPDFReportTheme.objects.update(owner=owner)

    def reverse_sync_themes(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='dosimeterpdfreporttheme',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosimeter_pdf_themes', to='owners.Owner', verbose_name='Owner'),
        ),
        migrations.RunPython(sync_themes, reverse_sync_themes),

    ]
