# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20150604_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawhtml',
            name='body_da',
            field=models.TextField(null=True, verbose_name='HTML'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='body_en',
            field=models.TextField(null=True, verbose_name='HTML'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='body_nn',
            field=models.TextField(null=True, verbose_name='HTML'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='body_sv',
            field=models.TextField(null=True, verbose_name='HTML'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='name_da',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='name_nn',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='rawhtml',
            name='name_sv',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
