# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20171024_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawhtml',
            name='name_da',
        ),
        migrations.RemoveField(
            model_name='rawhtml',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='rawhtml',
            name='name_nn',
        ),
        migrations.RemoveField(
            model_name='rawhtml',
            name='name_sv',
        ),
    ]
