# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20171026_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityRadonRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avglevel', models.IntegerField(default=0, verbose_name='Avg level')),
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('municipality', models.CharField(max_length=255, unique=True, verbose_name='Municipality')),
            ],
        ),
    ]
