# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_municipalityradonrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalityradonrisk',
            name='municipality_da',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='municipalityradonrisk',
            name='municipality_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='municipalityradonrisk',
            name='municipality_nn',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='municipalityradonrisk',
            name='municipality_sv',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Municipality'),
        ),
    ]
