# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20180109_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalityradonrisk',
            name='municipality_da',
        ),
        migrations.RemoveField(
            model_name='municipalityradonrisk',
            name='municipality_en',
        ),
        migrations.RemoveField(
            model_name='municipalityradonrisk',
            name='municipality_nn',
        ),
        migrations.RemoveField(
            model_name='municipalityradonrisk',
            name='municipality_sv',
        ),
    ]
